export {default as pieceReceipt} from './pieceReceipt.route.js'
export {default as tableLot} from './tabletLot.route.js'
export {default as defectEntry} from './defectEntry.js'
export {default as foldingPendinglist} from './foldingPending.route.js'
export {default as pieceFoldingEntry} from './pieceFoldingEntry.route.js'